// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ3Gaz5JceuTeZJySPXfZ-d-VKpYOD2N0',
    appId: '1:889483780911:web:6f78b492a42ec6911477da',
    messagingSenderId: '889483780911',
    projectId: 'chat-think-7463f',
    authDomain: 'chat-think-7463f.firebaseapp.com',
    storageBucket: 'chat-think-7463f.appspot.com',
    measurementId: 'G-JFDFQJM12T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk_hZHt6hVq9Vo9torf3dRYgd_l-CQN_4',
    appId: '1:889483780911:android:0f3e7307b5ed81091477da',
    messagingSenderId: '889483780911',
    projectId: 'chat-think-7463f',
    storageBucket: 'chat-think-7463f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYgFcEYjWWZ8RGV-sIsKjBRygMBA0LuzA',
    appId: '1:889483780911:ios:03e0b1a1022b4b811477da',
    messagingSenderId: '889483780911',
    projectId: 'chat-think-7463f',
    storageBucket: 'chat-think-7463f.appspot.com',
    iosBundleId: 'com.ankitD.thinkChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYgFcEYjWWZ8RGV-sIsKjBRygMBA0LuzA',
    appId: '1:889483780911:ios:af38a0f8654c37221477da',
    messagingSenderId: '889483780911',
    projectId: 'chat-think-7463f',
    storageBucket: 'chat-think-7463f.appspot.com',
    iosBundleId: 'com.example.thinkChat.RunnerTests',
  );
}
